#!/bin/bash

echo "🚀 QUICK COOLIFY DEPLOYMENT FIX"
echo "==============================="
echo ""
echo "🔍 ISSUE DIAGNOSIS:"
echo "=================="
echo "✅ Coolify Server: Running (128.140.111.171)"
echo "✅ Traefik Proxy: Running"
echo "❌ Main API Service: running:unhealthy"
echo "❌ Test Service: exited:unhealthy"
echo ""
echo "🔧 ROOT CAUSE:"
echo "============="
echo "• Main API is configured as nginx:alpine (static server)"
echo "• But Coolify expects a /health endpoint on port 8080"
echo "• nginx:alpine doesn't provide health check endpoints"
echo "• Test service has crashed completely"
echo ""
echo "🛠️  QUICK FIXES:"
echo "==============="
echo ""
echo "OPTION 1 - DISABLE HEALTH CHECK (RECOMMENDED)"
echo "============================================="
echo "If you want to run a static site:"
echo "1. Go to Coolify Dashboard"
echo "2. Navigate to: doctorhealthy1-api service"
echo "3. Click 'Edit' or 'Settings'"
echo "4. Find 'Health Check' section"
echo "5. Disable/Turn off health checks"
echo "6. Click 'Save' and redeploy"
echo ""
echo "OPTION 2 - FIX FOR GO APPLICATION"
echo "================================="
echo "If you want to run the Go backend:"
echo "1. Go to Coolify Dashboard"
echo "2. Edit doctorhealthy1-api service"
echo "3. Change 'Static Image' from 'nginx:alpine' to empty"
echo "4. Ensure 'Dockerfile' exists in your repository root"
echo "5. Set 'Base Directory' to '/'"
echo "6. Set 'Start Command' to './nutrition-platform' (Go binary)"
echo "7. Redeploy service"
echo ""
echo "OPTION 3 - RESTART TEST SERVICE"
echo "==============================="
echo "1. Go to Coolify Dashboard"
echo "2. Find the test service (dockerfile-*)"
echo "3. Click 'Restart' or 'Redeploy'"
echo ""
echo "📋 VERIFICATION:"
echo "==============="
echo "After fixes, run health check again:"
echo "• Main API: https://my.doctorhealthy1.com"
echo "• Test Service: http://vc40okgosockc8c8sgoko0k0.128.140.111.171.sslip.io"
echo ""
echo "🔍 MONITORING:"
echo "============="
echo "Use the Coolify MCP server I created to monitor:"
echo "• Check connection: coolify check_connection"
echo "• View all services: coolify get_services"
echo "• Health overview: coolify health_check"
echo ""
echo "📞 NEED HELP?"
echo "============="
echo "If issues persist, I can help you:"
echo "• Fix the Dockerfile configuration"
echo "• Implement proper health checks"
echo "• Debug container logs"
echo "• Set up proper monitoring"
echo ""
echo "✅ SETUP COMPLETE"
echo "================"
echo "Your Coolify MCP server is ready to use!"
echo "Run: ./fix-coolify-healthcheck.sh for detailed instructions"

