name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Run Auto-Fix Agent
      run: |
        cd backend/models
        chmod +x AUTO-FIX-AGENT.sh
        ./AUTO-FIX-AGENT.sh
    
    - name: Run Parallel Tests
      run: |
        cd backend/models
        chmod +x PARALLEL-TEST-RUNNER.sh
        ./PARALLEL-TEST-RUNNER.sh
    
    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        files: ./backend/logs/tests/*_coverage.out

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build Backend
      run: |
        cd backend
        go build -o bin/server ./cmd/server
    
    - name: Build Docker Image
      run: |
        cd backend
        docker build -t nutrition-platform:${{ github.sha }} .
    
    - name: Save Docker Image
      run: |
        docker save nutrition-platform:${{ github.sha }} | gzip > image.tar.gz
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: image.tar.gz

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Security Scan
      run: |
        cd backend/models
        chmod +x SECURITY-SCAN.sh
        ./SECURITY-SCAN.sh

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [test, build, security]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: docker-image
    
    - name: Deploy to Production
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        cd backend/models
        chmod +x SSH-DEPLOY.sh
        ./SSH-DEPLOY.sh
